services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Madrid

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure
    environment:
      - TZ=Europe/Madrid

volumes:
  postgres-data:
